name: Release
on:
  push:
    branches:
      - master
      - develop

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> .npmrc
      - name: install dependencies
        run: pnpm install
      - name: run tests
        if: github.ref == 'refs/heads/master'
        run: pnpm test
      - name: copy readme to every package
        run: echo "./packages/core/ ./packages/ui/" | xargs -n 1 cp README.md

      - name: Create Pre-release
        if: github.ref == 'refs/heads/develop'
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: pre-release version bump"
          title: "Pre-release version bump"
          publish: pnpm publish --tag next --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: release version bump"
          title: "Release version bump"
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
